    <?php if (isset($this->results)): ?>
        <h2><?php echo Clean::deuristub($this->city); ?></h2>
        <h5>Showing <strong><?php echo count($this->results); ?></strong> matching jobs</h5>
        <?php if (!empty($this->results)): ?>
        <ul id="searchresults">
            <?php
            $alt = false;
            foreach ($this->results as $result):

                $date_posted = $result['date_posted'];
                $location = $result['location'];
                $category = $result['category']);
                $schedule = $result['schedule'];
                $name = $result['name'];

                // fix the date
                $date_posted = (int) trim($date_posted);
            ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    <span class="date"><?php echo !empty($date_posted) ? date('m/d/Y', $date_posted) : ''; ?></span>
                    <?php
                    $url = '/job/details/';
                    if (!empty($location)) $url .= Clean::uristub($location) . '/';
                    if (!empty($category)) $url .= Clean::uristub($category) . '/';
                    $url .= Clean::uristub($result['uristub']) . '/';
                    ?>
                    <h3 class="job-title"><a href="<?php echo $url; ?>" class="job-title"><?php echo Clean::xss($name); ?></a></h3>
<!--                    <a href="<?php echo $url; ?>" class="right">View Details</a>-->
                    <?php if (!empty($schedule)): ?>
<!--                    <span class="schedule"><?php echo Clean::xss($schedule); ?></span>-->
                    <?php endif; ?>

                    <?php if (!empty($location)): ?>
                    <span class="location"><?php echo Clean::xss($location); ?></span>
                    <?php endif; ?>
                </li>
                <?php $alt = !$alt; ?>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <p>No jobs currently exist for the specified location.</p>
        <?php endif; ?>
    <?php else: ?>
        <?php if (!empty($this->cities)): ?>
            <h2>Job Cities</h2>
            <ul class="alternating">
                <?php $alt = false; ?>
                <?php foreach ($this->cities as $city): ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    <?php $url = '/jobs/city/' . Clean::uristub($city['city']) . '/'; ?>
                    <a href="<?php echo $url; ?>"><?php echo Clean::xss($city['city']); ?></a>
                </li>
                <?php $alt = !$alt; ?>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <h3>No cities currently exist</h3>
            <p>It does not appear as though any jobs currently exist.</p>
        <?php endif; ?>
    <?php endif; ?>