<div class="pageWrapper">
        
        <div class="header">
            <a href="http://www.phoenix.edu/" target="blank"><img src="http://seostatic.tmp.com/job-images/3326/UP_logo.jpg" alt="University of Phoenix" /></a>

<ul>
    <li class="first"><a href="http://www.phoenix.edu/faculty/become-a-faculty-member/doctoral-become-a-faculty-member.html" target="_blank">Become a Doctoral Faculty Member</a></li>
    <li><a href="http://www.phoenix.edu/faculty/become-a-faculty-member/teach-online-become-faculty-member.html" target="_blank">Become an Online Faculty Member</a></li>
    <li class="last"><a href="http://www.phoenix.edu/faculty/become-a-faculty-member.html" target="_blank">Become a Campus Faculty Member</a></li>
</ul>
        </div><!--/.header-->
    
        <div class="wrapper_contents">
            
        
        <div class="banner">
                <div class="bannerImg">
                    <img src="http://seostatic.tmp.com/job-images/3326/L1header.jpg" alt="Ellis Jones, M.A."/>
                    <p><span class="name">Ellis Jones, M.A.</span><br />School of Business</p>
                </div>
                <h3>Have your job<br />and teach it too.</h3>
                <h4>Does this sound like you?</h4>
                <p>You're an expert in your field with years of real-world experience you'd love to share with eager learners. You'd be a terrific instructor at the college level, but you're thriving in your present career and don't want to leave. Well, you're in luck.</p>
<p>At University of Phoenix, our flexible class schedules mean you can teach for us part-time without interrupting your full-time career.</p>
</div><!--/.banner-->

            <div class="contents">
            <div id="col-left">
            <ul>
<li><a href="/category">Search by Category</a></li>
<li><a href="/location">Search by Location</a></li>
<li><a href="/jobs/all">Browse All Jobs </a></li>
<li><a href="/index">Home </a></li></ul></div></ul></div>
<div id="col-center">
 <div class="wrapper content">
    <?php if (isset($this->results)): ?>
    <div class="leftcolumn">
        <h2>Showing All Jobs</h2>
        <?php if (!empty($this->results)): ?>
        <ul id="searchresults">
            <?php
            $alt = false;
            foreach ($this->results as $result):
                $id = $result['id'];
                $date_posted = $result['date_posted'];
                $location = $result['location'];
                $category = $result['category'];
                $schedule = $result['schedule'];
            ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    <span class="date"><?php echo !empty($date_posted) ? date('F j Y', $date_posted) : ''; ?></span>
                    <h3 class="job-title"><?php echo Clean::xss($result['name']); ?></h3>
                    <?php
                    $url = '/job/details/';
                    if (!empty($location)) $url .= Clean::uristub($location) . '/';
                    if (!empty($category)) $url .= Clean::uristub($category) . '/';
                    $url .= Clean::uristub($result['uristub']) . '/';
                    ?>
                    <a href="<?php echo $url; ?>" class="right">View Details</a>
                    <?php if (!empty($schedule)): ?>
                    <span class="schedule"><?php echo Clean::xss($schedule); ?></span>
                    <?php endif; ?>

                    <?php if (!empty($location)): ?>
                    <span class="location"><?php echo Clean::xss($location); ?></span>
                    <?php endif; ?>
                </li>
                <?php $alt = !$alt; ?>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <h3>No search results were found</h3>
        <p>No search results were found matching your criteria. Please consider
        loosening your search criteria and try again.</p>
        <?php endif; ?>
    </div>
    <div class="rightcolumn">
        <?php if (!empty($this->jobsInCategory)): ?>
            <h4>Other Jobs In This Categoryaaa</h4>
            <ul>
                <li><a href="/job/details/<?php echo Clean::xss($job['uristub']); ?>"><?php echo Clean::xss($job['name']); ?></a></li>
            </ul>
        <?php endif; ?>

        <?php if (!empty($this->jobsInLocation)): ?>
            <h4>Other Jobs At This Locationbbb</h4>
            <ul>
                <?php foreach ($this->jobsInLocation as $job): ?>
                <li><a href="/job/details/<?php echo Clean::xss($job['uristub']); ?>"><?php echo Clean::xss($job['name']); ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php else: ?>
    <div class="leftcolumn">
        <?php echo $this->partial('partials/global/flash-messenger.phtml');?>
    </div>
    <?php endif; ?>
</div>
</div>
<div id="col-right">  
<h3>Search our Jobs</h3>
<form method="post" action="/search/" class="searchbar">
            <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
            <button type="submit" id="submit" value="search">Go</button>
            <br />
</form>

 <div class="box links">
                    <div class="inbox">
                    
<script type="text/javascript">addthis_pub = '';addthis_language='en';</script>

<a href="http://www.addthis.com/bookmark.php" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" 
onmouseout="addthis_close()" onclick="return addthis_sendto()">
<img src="http://s7.addthis.com/static/btn/lg-share-en.gif" width="125" height="16" border="0" alt="" /></a>
<script type="text/javascript" src="http://s7.addthis.com/js/152/addthis_widget.js"></script>
<h3>Useful Links</h3>
                        <ul><li><a href="http://www.phoenix.edu/about_us/about_university_of_phoenix.html" target="_blank">About Us</a><br /></li><li><a href="http://www.phoenix.edu/campus-locations.html" target="_blank">Campus Locations</a><br /></li><li><a href="http://www.phoenix.edu/faculty/become_a_faculty_member/faculty-faq.html" target="_blank">Faculty FAQ’s</a><br /></li><li><a href="http://www.facultymatters.com/summer12" target="_blank">Faculty Matters magazine</a><br /></li><li><a href="http://facultyjobs-phoenix.com/article/facultyprofiles" target="_blank">Meet the Faculty</a><br /></li></ul>
                    </div><!--/.inbox-->
                </div><!--/.box .links--></div>
</div>
            
            
         

         
            <div class="clear"></div>
        </div><!--/.wrapper-->
    </div>