<div id="header">
    <h1 id="logo">
        <a href="/">
            <?php echo !empty($this->theme['logo']) ? '<img src="' . $this->theme['logo'] . '" alt="' . (!empty($this->theme['company']) ? Clean::xss($this->theme['company']) : '') . '" />' : ''; ?>
            <?php echo !empty($this->theme['company']) ? '<span>' . Clean::xss($this->theme['company']) . '</span>' : '<span>JobCastle</span>'; ?>
        </a>
    </h1>
</div>
<div id="searchblock" class="clearfix">
    <div class="wrapper">
    <div id="page" class="hfeed">
	<header id="branding" role="banner">
			<hgroup>
				<div><div class="menu-top-menu-container"><ul id="menu-top-menu" class="menu"><li id="menu-item-20" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-20"><a href="http://frontrangejobs.com/">Home</a></li>
<li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21"><a href="http://frontrangejobs.com/contact">Contact</a></li>
<li id="menu-item-22" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-22"><a href="http://www.frontrange.edu">Visit Frontrange.edu</a></li>
</ul></div></div>
			</hgroup><!-- #access -->
	</header><!-- #branding -->

	<div id="main"><div id="primary_about">
	<div id="content" role="main"><!-- #post-103 -->

						<div id="comments"><!-- #respond -->
						
</div><!-- #comments -->

				
			</div><!-- #content -->
		</div><!-- #primary --></div><!-- #main -->

	<!-- #colophon -->
</div>
        <form method="post" action="/search/" class="searchbar">
            <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
            <button type="submit" id="submit" value="search">search</button>
                 <span class="filter"><br />filter results by:</span>
            <?php if (!empty($this->searchterm)): ?>
            <span>Search results for '<?php echo Clean::xss(substr($this->searchterm, 0, 32)); ?>'</span>
            <?php endif; ?>
            <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
                <?php
                  $dropEntry = '<option value=""></option>';
                foreach ($this->dropdownLocations as $dropdownLocations): 
                  $val = Clean::uristub($dropdownLocations['location']);
                  $dropEntry .= '<option value="' . urlencode($dropdownLocations['location']) . '"';
                  $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
                  $dropEntry .= Clean::xss($dropdownLocations['location']);
                  $dropEntry .= '</option><br />'; 
                  endforeach; 
                  echo $dropEntry;
                  ?>
            </select>
            <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
                <?php
                  $dropEntry = '<option value=""></option>';
                foreach ($this->dropdownCategories as $dropdownCategories): 
                  $val = Clean::uristub($dropdownCategories['category']);
                  $dropEntry .= '<option value="' . urlencode($dropdownCategories['category']) . '"';
                  $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
                  $dropEntry .= Clean::xss($dropdownCategories['category']);
                  $dropEntry .= '</option><br />'; 
                  endforeach; 
                  echo $dropEntry;
                  ?>
            </select>
            <?php if (empty($this->searchterm)): ?>
       
            <?php endif; ?>
        </form><div id="pagesearch"><div class="searchbox_header_page pagebox" id="category">
<h3><a href="/category">Search Jobs by Category</a></h3>
</div><div class="searchbox_header_page pagebox" id="location">
<h3><a href="/location">Search Jobs by Location</a></h3>
</div><div class="searchbox_header_page pagebox" id="listings">
<h3><a href="/jobs/all">Search Recent Listings</a></h3>
</div>
</div>
    </div>
</div>
<div class="wrapper content">
    <?php if (isset($this->results)): ?>
    <div class="leftcolumn">
        <h2>Showing All Jobs</h2>
        <?php if (!empty($this->results)): ?>
        <ul id="searchresults">
            <?php
            $alt = false;
            foreach ($this->results as $result):
                $id = $result['id'];
                $date_posted = $result['date_posted'];
                $location = $result['location'];
                $category = $result['category'];
                $schedule = $result['schedule'];
            ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    <span class="date"><?php echo !empty($date_posted) ? date('F j Y', $date_posted) : ''; ?></span>
                    <h3 class="job-title"><?php echo Clean::xss($result['name']); ?></h3>
                    <?php
                    $url = '/job/details/';
                    if (!empty($location)) $url .= Clean::uristub($location) . '/';
                    if (!empty($category)) $url .= Clean::uristub($category) . '/';
                    $url .= Clean::uristub($result['uristub']) . '/';
                    ?>
                    <a href="<?php echo $url; ?>" class="right">View Details</a>
                    <?php if (!empty($schedule)): ?>
                    <span class="schedule"><?php echo Clean::xss($schedule); ?></span>
                    <?php endif; ?>

                    <?php if (!empty($location)): ?>
                    <span class="location"><?php echo Clean::xss($location); ?></span>
                    <?php endif; ?>
                </li>
                <?php $alt = !$alt; ?>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <h3>No search results were found</h3>
        <p>No search results were found matching your criteria. Please consider
        loosening your search criteria and try again.</p>
        <?php endif; ?>
    </div>
    <div class="rightcolumn">
        <?php if (!empty($this->jobsInCategory)): ?>
            <h4>Other Jobs In This Categoryaaa</h4>
            <ul>
                <li><a href="/job/details/<?php echo Clean::xss($job['uristub']); ?>"><?php echo Clean::xss($job['name']); ?></a></li>
            </ul>
        <?php endif; ?>

        <?php if (!empty($this->jobsInLocation)): ?>
            <h4>Other Jobs At This Locationbbb</h4>
            <ul>
                <?php foreach ($this->jobsInLocation as $job): ?>
                <li><a href="/job/details/<?php echo Clean::xss($job['uristub']); ?>"><?php echo Clean::xss($job['name']); ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php else: ?>
    <div class="leftcolumn">
        <?php echo $this->partial('partials/global/flash-messenger.phtml');?>
    </div>
    <?php endif; ?>
</div>
<footer id="colophon" role="contentinfo">

			
			<div id="site-generator">
								©2010-2012 • FRONT RANGE COMMUNITY COLLEGE • 3645 WEST 112TH AVENUE • WESTMINSTER, CO 80031 • 303-404-5000
STATE OF COLORADO'S TRANSPARENCY ONLINE PROJECT SYSTEM (TOPS)
			</div>
	</footer>