<p>
Emailing <strong><?php echo $this->jobTitle; ?></strong>
</p>
<form method="post">
    <p>
        <label for="email">Email Address:</label>
        <input type="text" id="email" name="email" />
    </p>
    <p>
        <label for="addl-comments">Additional Comments:</label>
        <textarea name="addl-comments" id="addl-comments"></textarea>
    </p>
    <input type="submit" name="submit" value="Send" />
</form>
<p>
    <a href="<?php echo $this->jobLink; ?>">Back to Job Listing</a>
</p>