<?php
    /*
    $use_dynamic_number = ($this->job['dynamic_phone'] == 1 && !empty($this->theme['default_phone']));
    $number = ($this->job['dynamic_phone'] == 1) ? $this->theme['default_phone'] : ((!empty($this->job['apply_phone'])) ? $this->job['apply_phone'] : $this->theme['default_phone']);
    */
?>
<div id="container">
<div class="header">
<div><div class="menu-top-menu-container"><ul id="menu-top-menu" class="menu">
  <li id="menu-item-20" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-20"><a href="http://apollo.skookumx.com">Home</a></li>
<li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21"><a href="http://www.apollogrp.edu/careers/working-at-apollo-group">Working at Apollo Group</a></li>
<li id="menu-item-22" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-22"><a href="http://www.apollogrp.edu/careers/our-values">Our Values</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-22"><a href="http://www.apollogrp.edu/careers/benefits">Benefits</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-22"><a href="http://facultyjobs-phoenix.com/">Search Faculty Jobs</a></li>
</ul>
</div></div>

</div>
<div id="searchblock" class="clearfix">
    <div class="wrapper">
        <form method="post" action="/search/" class="searchbar">
            <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
            <button type="submit" id="submit" value="search"></button>
            <br />
            <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
                <?php
                  $dropEntry = '<option value=""></option>';
                foreach ($this->dropdownLocations as $dropdownLocations):
                  $val = Clean::uristub($dropdownLocations['location']);
                  $dropEntry .= '<option value="' . urlencode($dropdownLocations['location']) . '"';
                  $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
                  $dropEntry .= Clean::xss($dropdownLocations['location']);
                  $dropEntry .= '</option><br />';
                  endforeach;
                  echo $dropEntry;
                  ?>
            </select>
            <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
                <?php
                  $dropEntry = '<option value=""></option>';
                foreach ($this->dropdownCategories as $dropdownCategories):
                  $val = Clean::uristub($dropdownCategories['category']);
                  $dropEntry .= '<option value="' . urlencode($dropdownCategories['category']) . '"';
                  $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
                  $dropEntry .= Clean::xss($dropdownCategories['category']);
                  $dropEntry .= '</option><br />';
                  endforeach;
                  echo $dropEntry;
                  ?>
            </select>
        </form>
    </div>
</div>
<div class="wrapper content">
    <div class="leftcolumn">
        <?php if($this->hasSuccess) echo $this->partial('partials/global/flash-messenger.phtml'); ?>
        <?php if (!empty($this->job)): ?>
            <h1 class="left job-title"><?php echo Clean::xss($this->job['name']); ?></h1>
            <?php if (!empty($this->job['schedule'])): ?>
            <span class="left schedule"><?php echo Clean::xss($this->job['schedule']); ?></span>
            <?php endif; ?>

            <?php if (!empty($this->job['location'])): ?>
            <div class="location">Job Location: <?php echo Clean::xss($this->job['location']); ?></div>
            <?php endif; ?>

            <section class="job-details">
                <?php if (!empty($this->job['description'])): ?>
                
                <div class="description">
                <?php if (!isset($this->job['hide_apply']) || $this->job['hide_apply'] == 0): ?>
                    <?php $onClick = /*"_gaq.push(['_trackEvent', 'Apply Now top', 'Applies top', '" . Clean::xss($this->job['name']) . (!empty($this->job['location']) ? ', ' . Clean::xss($this->job['location']) : '') . "'])";*/'' ?>
                    <?php if (isset($this->job['modal_style']) && $this->job['modal_style'] == 'none'): ?>
                    <a target="_blank" href="<?php echo Clean::xss($this->job['apply_url']); ?>" class="btn apply_now" onClick="<?php echo $onClick; ?>">Apply Now</a>
                    <?php else: ?>
                    <a href="#applyNow" class="btn apply_now" rel="facebox" onClick="<?php echo $onClick; ?>">Apply Now</a>
                    <?php endif; ?>
                <?php endif; ?>
             <br />             
                <h3 class="heading">Position Summary</h3>
                    <?php
                    $description = str_replace(
                        array('&nbsp;', '<DIV></DIV>', '<DIV></SPAN></DIV>', '<div></div>'),
                        array('', '<br />'),
                        $this->job['description']
                    );
                    $description = str_replace('<br /><br />', '<br />', $description);

                    echo $description;

                    ?>
                </div>
                <?php endif; ?>

                <?php if (!empty($this->job['qualifications'])): ?>
                <h3 class="heading">Qualifications</h3>
                <div class="qualifications">
                    <?php
                    $qualifications = str_replace(
                        array('&nbsp;', '<DIV></DIV>', '<DIV></SPAN></DIV>', '<div></div>'),
                        array('', '<br />'),
                        $this->job['qualifications']
                    );
                    $qualifications = str_replace('<br /><br />', '<br />', $qualifications);
                    echo $qualifications;

                    ?>
                </div>
                <?php endif; ?>

                <?php
                if (!empty($this->job['shift'])
                    || !empty($this->job['schedule'])
                    || !empty($this->job['department'])):
                ?>
                    <h3 class="heading">Other Information</h3>
                    <ul>
                        <?php if (!empty($this->job['department'])): ?>
                        <li><strong>Department:</strong> <?php echo Clean::xss($this->job['department']); ?></li>
                        <?php endif; ?>
                        <?php if (!empty($this->job['shift'])): ?>
                        <li><strong>Shift:</strong> <?php echo Clean::xss($this->job['shift']); ?></li>
                        <?php endif; ?>
                        <?php if (!empty($this->job['schedule'])): ?>
                        <li><strong>Schedule:</strong> <?php echo Clean::xss($this->job['schedule']); ?></li>
                        <?php endif; ?>
                    </ul>
                <?php
                endif;
                ?>



                <?php if (!isset($this->job['hide_apply']) || $this->job['hide_apply'] == 0): ?>
                    <?php $onClick = /*"_gaq.push(['_trackEvent', 'Apply Now bottom', 'Applies bottom', '" . Clean::xss($this->job['name']) . (!empty($this->job['location']) ? ', ' . Clean::xss($this->job['location']) : '') . "'])"*/''; ?>
                    <?php if (isset($this->job['modal_style']) && $this->job['modal_style'] == 'none'): ?>
                    <a target="_blank" href="<?php echo Clean::xss($this->job['apply_url']); ?>" class="btn apply_now" onClick="<?php echo $onClick; ?>">Apply Now</a>
                    <?php else: ?>
                    <a href="#applyNow" class="btn apply_now" rel="facebox" onClick="<?php echo $onClick; ?>">Apply Now</a>
                    <?php endif; ?>
                <?php endif; ?>

            </section>

        <?php else: ?>
        <h3 class="heading">This Job No Longer Exists</h3>
        <p>We're sorry, but it appears as though the job you are looking for
        no longer exists.</p>
        <?php endif; ?>
    </div>

    <div class="rightcolumn">
    <div id="sharetools"><h4>Share This</h4>
   <span style="margin-left:5px;" class='st_sharethis_large' displayText='ShareThis'></span>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_linkedin_large' displayText='LinkedIn'></span>
<span class='st_email_large' displayText='Email'></span>
</div>
<?php if (!empty($this->jobsInCategory)): ?>
      <h4>Other Jobs In This Category</h4>
            <ul>
                <?php

                foreach ($this->jobsInCategory as $job):
                    $id = $job['id'];
                    $name = $job['name'];
                    $uristub = $job['uristub'];
                    $location = $job['location'];
                    $category = $job['category'];
                                    ?>
                <?php if ($id !== $this->job['id']): ?>
                <?php
                $url = '/job/details/';
                if (!empty($location)) $url .= Clean::uristub($location) . '/';
                if (!empty($category)) $url .= Clean::uristub($category) . '/';
                $url .= $uristub . '/';
                ?>
                <li><a href="<?php echo $url; ?>"><?php echo Clean::xss($name); ?></a></li>
                <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php if (!empty($this->jobsInLocation)): ?>
            <h4>Other Jobs At This Location</h4>
            <ul>
                <?php
                foreach ($this->jobsInLocation as $job):
                    $id = $job['id'];
                    $name = $job['name'];
                    $uristub = $job['uristub'];
                    $location = $job['location'];
                    $category = $job['category'];
                ?>
                <?php if ($id != $this->job['id']): ?>
                <?php
                $url = '/job/details/';
                if (!empty($location)) $url .= Clean::uristub($location) . '/';
                if (!empty($category)) $url .= Clean::uristub($category) . '/';
                $url .= $uristub . '/';
                ?>
                <li><a href="<?php echo $url; ?>"><?php echo Clean::xss($name); ?></a></li>
                <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <div id="current_openings_about">
                  <h4>Recent Job Listings</h4>
                    <?php if (!empty($this->recent)): ?>
                  <ul>
            <?php foreach ($this->recent as $recent): ?>
            <?php
            $url = '/job/details/';
            if (!empty($recent['location'])) $url .= Clean::uristub($recent['location']) . '/';
            if (!empty($recent['category'])) $url .= Clean::uristub($recent['category']) . '/';
            $url .= Clean::uristub($recent['uristub']) . '/';
            ?>
          <li><a href="<?php echo $url; ?>"><?php echo Clean::xss($recent['name']); ?></a></li>
            <?php endforeach; ?>
            <li>
                <a href="/jobs/all" class="btn">See All Jobs</a>
            </li>
        </ul>
        <?php else: ?>
        <p>No recent listings exist.</p>
      <?php endif; ?></div>
    </div>
</div>

<div id="applyNow" style="display:none">
    <h4>Apply Now</h4>
    <?php if($this->hasError) echo $this->partial('partials/global/flash-messenger.phtml'); ?>
    <form method="post" action="" enctype="multipart/form-data" name="formApplyNow" id="formApplyNow">
        <?php /*if (isset($this->job['modal_style']) && $this->job['modal_style'] == 'phone' && ($use_dynamic_number || !empty($this->job['apply_phone']))): ?>
        <div class="call">
            <h5 class="call_heading">Please Call:</h5>
            <h1><?php echo Clean::xss($number); ?></h1>
        </div>

        <h6 class="sep">OR</h6>
        <h5 class="call_heading">Apply Online:</h5>
        <?php endif;*/ ?>
        <p>
            <label for="name">Name*:</label>
            <input type="text" class="text" name="name" id="name" placeholder="Enter your full name" value="<?php echo !empty($this->applynow['name']) ? Clean::xss($this->applynow['name']) : ''; ?>" />
        </p>
        <p>
            <label for="name">Email Address*:</label>
            <input type="text" class="text" name="email" id="email" placeholder="Enter your email address" value="<?php echo !empty($this->applynow['email']) ? Clean::xss($this->applynow['email']) : ''; ?>" />
        </p>
        <p>
            <label for="previous_job_title">Current Job Title:</label>
            <input type="text" class="text" name="previous_job_title" id="previous_job_title" placeholder="Current Job Title" value="<?php echo !empty($this->applynow['previous_job_title']) ? Clean::xss($this->applynow['previous_job_title']) : ''; ?>" />
        </p>
        <?php if (isset($this->job['editable']) && $this->job['editable'] == 1 && $this->job['modal_style'] != 'phone'): ?>
        <p>
            <label for="name">Cover Letter:</label>
            <textarea name="cover_letter" id="cover_letter"><?php echo !empty($this->applynow['cover_letter']) ? Clean::xss($this->applynow['cover_letter']) : ''; ?></textarea>
        </p>
        <p>
            <label for="resume">Resume:</label>
            <input type="file" name="resume" id="resume" />
        </p>
        <?php endif; ?>
        <p>
            <input type="hidden" name="job_id" id="job_id" value="<?php echo !empty($this->job['id']) ? $this->job['id'] : ''; ?>" />
            <input type="hidden" name="client_id" id="client_id" value="<?php echo !empty($this->job['created_by']) ? $this->job['created_by'] : ''; ?>" />
            <button type="submit" name="appyBtn" class="btn" value="Continue">Continue</button><br />
            <?php if (isset($this->job['editable']) && $this->job['editable'] == 1): ?>
            <span class="note">Please be patient while your resume is uploaded</span>
            <?php endif; ?>
        </p>
    </form>
</div>
</div>

<?php if($this->hasError): ?>
<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">
$(function() {
    $.facebox({ div: '#applyNow' });
});
</script>
<?php $this->placeholder('js')->captureEnd(); ?>
<?php endif; ?>

<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">
$(function() {
    $('a[rel=facebox]').facebox();
});
// sharethis
var switchTo5x=true;
var __st_loadLate=true;
</script>


<script type="text/javascript">var switchTo5x=false;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "c36338a3-e3fd-442a-8b3d-d2df8fb9103b"});</script>

<?php /*if($use_dynamic_number && !empty($this->theme['dynamic_phone_tracking'])) echo $this->theme['dynamic_phone_tracking'];*/ ?>

<?php $this->placeholder('js')->captureEnd(); ?>
