        <?php if($this->hasSuccess) echo $this->partial('partials/global/flash-messenger.phtml'); ?>
        <?php if (!empty($this->job)): ?>
            <h1 class="left job-title"><?php echo ($this->job['name']); ?></h1>
            <?php $state = $this->job['state']; ?>
            <?php if (!empty($this->job['schedule'])): ?>
            <span class="left schedule"><?php echo Clean::xss($this->job['schedule']); ?></span>
            <?php endif; ?>

            <?php if (!empty($this->job['location'])): ?>
            <div class="location">Job Location: <?php echo Clean::xss($this->job['location']); ?></div>
            <?php endif; ?>

            <section class="job-details">
                <?php if (!empty($this->job['description'])): ?>

                <div class="description">
                <?php if (!isset($this->job['hide_apply']) || $this->job['hide_apply'] == 0): ?>
                    <?php $onClick = /*"_gaq.push(['_trackEvent', 'Apply Now top', 'Applies top', '" . Clean::xss($this->job['name']) . (!empty($this->job['location']) ? ', ' . Clean::xss($this->job['location']) : '') . "'])";*/'' ?>
                    <?php if (isset($this->job['modal_style']) && $this->job['modal_style'] == 'none'): ?>
                    <a target="_blank" href="<?php echo Clean::xss($this->job['apply_url']); ?>" class="btn apply_now" onClick="<?php echo $onClick; ?>">Apply Now »</a>
                    <?php else: ?>
                    <a href="#applyNow" class="btn apply_now" rel="facebox" onClick="<?php echo $onClick; ?>">Apply Now »</a>
                    <?php endif; ?>
                <?php endif; ?>
             <br />
                <h3 class="heading">Position Summary</h3>
                    <?php
                    $description = str_replace(
                        array('&nbsp;', '<DIV></DIV>', '<DIV></SPAN></DIV>', '<div></div>'),
                        array('', '<br />'),
                        $this->job['description']
                    );
                    $description = str_replace('<br /><br />', '<br />', $description);

                    echo $description;

                    ?>
                </div>
                <?php endif; ?>

                <?php if (!empty($this->job['qualifications'])): ?>
                <h3 class="heading">Qualifications</h3>
                <div class="qualifications">
                    <?php
                    $qualifications = str_replace(
                        array('&nbsp;', '<DIV></DIV>', '<DIV></SPAN></DIV>', '<div></div>'),
                        array('', '<br />'),
                        $this->job['qualifications']
                    );
                    $qualifications = str_replace('<br /><br />', '<br />', $qualifications);
                    echo $qualifications;

                    ?>
                </div>
                <?php endif; ?>

                <?php
                if (!empty($this->job['shift'])
                    || !empty($this->job['schedule'])
                    || !empty($this->job['department'])):
                ?>
                    
                <?php
                endif;
                ?>



                <?php if (!isset($this->job['hide_apply']) || $this->job['hide_apply'] == 0): ?>
                    <?php $onClick = /*"_gaq.push(['_trackEvent', 'Apply Now bottom', 'Applies bottom', '" . Clean::xss($this->job['name']) . (!empty($this->job['location']) ? ', ' . Clean::xss($this->job['location']) : '') . "'])"*/''; ?>
                    <?php if (isset($this->job['modal_style']) && $this->job['modal_style'] == 'none'): ?>
                    <a target="_blank" href="<?php echo Clean::xss($this->job['apply_url']); ?>" class="btn apply_now" onClick="<?php echo $onClick; ?>">Apply Now »</a>
                    <?php else: ?>
                    <a href="#applyNow" class="btn apply_now" rel="facebox" onClick="<?php echo $onClick; ?>">Apply Now »</a>
                    <?php endif; ?>
                <?php endif; ?>

            </section>

        <?php else: ?>
        <h3 class="heading">This Job No Longer Exists</h3>
        <p>We're sorry, but it appears as though the job you are looking for
        no longer exists.</p>
        <?php endif; ?>
<!--
<div id="applyNow" style="display:none">
    <h4>Apply Now</h4>
    <?php if($this->hasError) echo $this->partial('partials/global/flash-messenger.phtml'); ?>
    <form method="post" action="" enctype="multipart/form-data" name="formApplyNow" id="formApplyNow">
        <?php /*if (isset($this->job['modal_style']) && $this->job['modal_style'] == 'phone' && ($use_dynamic_number || !empty($this->job['apply_phone']))): ?>
        <div class="call">
            <h5 class="call_heading">Please Call:</h5>
            <h1><?php echo Clean::xss($number); ?></h1>
        </div>

        <h6 class="sep">OR</h6>
        <h5 class="call_heading">Apply Online:</h5>
        <?php endif;*/ ?>
        <p>
            <label for="name">Name*:</label>
            <input type="text" class="text" name="name" id="name" placeholder="Enter your full name" value="<?php echo !empty($this->applynow['name']) ? Clean::xss($this->applynow['name']) : ''; ?>" />
        </p>
        <p>
            <label for="name">Email Address*:</label>
            <input type="text" class="text" name="email" id="email" placeholder="Enter your email address" value="<?php echo !empty($this->applynow['email']) ? Clean::xss($this->applynow['email']) : ''; ?>" />
        </p>
        <p>
            <label for="previous_job_title">Current Job Title:</label>
            <input type="text" class="text" name="previous_job_title" id="previous_job_title" placeholder="Current Job Title" value="<?php echo !empty($this->applynow['previous_job_title']) ? Clean::xss($this->applynow['previous_job_title']) : ''; ?>" />
        </p>
        <?php if (isset($this->job['editable']) && $this->job['editable'] == 1 && $this->job['modal_style'] != 'phone'): ?>
        <p>
            <label for="name">Cover Letter:</label>
            <textarea name="cover_letter" id="cover_letter"><?php echo !empty($this->applynow['cover_letter']) ? Clean::xss($this->applynow['cover_letter']) : ''; ?></textarea>
        </p>
        <p>
            <label for="resume">Resume:</label>
            <input type="file" name="resume" id="resume" />
        </p>
        <?php endif; ?>
        <p>
            <input type="hidden" name="job_id" id="job_id" value="<?php echo !empty($this->job['id']) ? $this->job['id'] : ''; ?>" />
            <input type="hidden" name="client_id" id="client_id" value="<?php echo !empty($this->job['created_by']) ? $this->job['created_by'] : ''; ?>" />
            <button type="submit" name="appyBtn" class="btn" value="Continue">Continue</button><br />
            <?php if (isset($this->job['editable']) && $this->job['editable'] == 1): ?>
            <span class="note">Please be patient while your resume is uploaded</span>
            <?php endif; ?>
        </p>
    </form><div id="pagesearch"><div class="searchbox_header_page pagebox" id="category">
<h3><a href="/category">Search Jobs by Category</a></h3>
</div><div class="searchbox_header_page pagebox" id="location">
<h3><a href="/location">Search Jobs by Location</a></h3>
</div><div class="searchbox_header_page pagebox" id="listings">
<h3><a href="/jobs/all">Search Recent Listings</a></h3>
</div>
</div>
</div>
</div>
-->

<?php if($this->hasError): ?>
<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">
$(function() {
    $.facebox({ div: '#applyNow' });
});
</script>
<?php $this->placeholder('js')->captureEnd(); ?>
<?php endif; ?>

<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">
$(function() {
    $('a[rel=facebox]').facebox();
});
</script>
<?php $this->placeholder('js')->captureEnd(); ?>
