<div class="pageWrapper">
        
        <div class="header">
            <a href="http://www.phoenix.edu/" target="blank"><img src="http://seostatic.tmp.com/job-images/3326/UP_logo.jpg" alt="University of Phoenix" /></a>

<ul>
    <li class="first"><a href="http://www.phoenix.edu/faculty/become-a-faculty-member/doctoral-become-a-faculty-member.html" target="_blank">Become a Doctoral Faculty Member</a></li>
    <li><a href="http://www.phoenix.edu/faculty/become-a-faculty-member/teach-online-become-faculty-member.html" target="_blank">Become an Online Faculty Member</a></li>
    <li class="last"><a href="http://www.phoenix.edu/faculty/become-a-faculty-member.html" target="_blank">Become a Campus Faculty Member</a></li>
</ul>
        </div><!--/.header-->
    
        <div class="wrapper_contents">
            
        
        <div class="banner">
                <div class="bannerImg">
                    <img src="http://seostatic.tmp.com/job-images/3326/L1header.jpg" alt="Ellis Jones, M.A."/>
                    <p><span class="name">Ellis Jones, M.A.</span><br />School of Business</p>
                </div>
                <h3>Have your job<br />and teach it too.</h3>
                <h4>Does this sound like you?</h4>
                <p>You're an expert in your field with years of real-world experience you'd love to share with eager learners. You'd be a terrific instructor at the college level, but you're thriving in your present career and don't want to leave. Well, you're in luck.</p>
<p>At University of Phoenix, our flexible class schedules mean you can teach for us part-time without interrupting your full-time career.</p>
</div><!--/.banner-->

            <div class="contents">
            <div id="col-left">
            <ul>
<li><a href="/category">Search by Category</a></li>
<li><a href="/location">Search by Location</a></li>
<li><a href="/jobs/all">Browse All Jobs </a></li>
<li><a href="/index">Home </a></li></ul></div></ul></div>
<div id="col-center">
<div class="wrapper content">
    <?php if (isset($this->results)): ?>
    <div class="leftcolumn">
        <h2><?php echo Clean::deuristub($this->category); ?></h2>
        <h5>Showing <strong><?php echo count($this->results); ?></strong> matching jobs</h5>
        <?php if (!empty($this->results)): ?>
        <ul id="searchresults">
            
            <?php
            $alt = false;
            foreach ($this->results as $result):
                $date_posted = $result['date_posted'];
                $location = $result['location'];
                $category = $result['category'];
                $schedule = $result['schedule'];

                // fix the date
                $date_posted = (int) trim($date_posted);
            ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    <span class="date"><?php echo !empty($date_posted) ? date('F j Y', $date_posted) : ''; ?></span>
                    <h3 class="job-title"><?php echo $result['name']; ?></h3>
                    <?php
                    $url = '/job/details/';
                    if (!empty($location)) $url .= Clean::uristub($result['location']) . '/';
                    if (!empty($category)) $url .= Clean::uristub($result['category']) . '/';
                    $url .= $result['uristub'] . '/';
                    ?>
                    <a href="<?php echo $url; ?>" class="right">View Details</a>
                    <?php if (!empty($schedule)): ?>
                    <span class="schedule"><?php echo $result['schedule']; ?></span>
                    <?php endif; ?>

                    <?php if (!empty($location)): ?>
                    <span class="location"><?php echo $result['location']; ?></span>
                    <?php endif; ?>
                </li>
                <?php $alt = !$alt; ?>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <p>No jobs currently exist in the specified category.</p>
        <?php endif; ?>
    </div>
    <?php else: ?>
        <div class="leftcolumn">
        <?php if (!empty($this->categories)): ?>
            <h2>Job Categories</h2>
            <ul class="alternating">
                <?php $alt = false; ?>
                <?php foreach ($this->categories as $category): ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    
                    <?php
                    $url = '/jobs/' . str_replace("%2F", "_", urlencode($category['category'])) . '/';
                    ?>
                    <a href="<?php echo $url; ?>"><?php echo Clean::xss($category['category']); ?></a>
                </li>
                <?php $alt = !$alt; ?>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <h3>No categories currently exist</h3>
            <p>It does not appear as though any jobs currently exist.</p>
        <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php if (!empty($this->locations)): ?>
    <?php endif; ?>
</div></div><div id="col-right">  
<h3>Search our Jobs</h3>
<form method="post" action="/search/" class="searchbar">
            <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
            <button type="submit" id="submit" value="search">search</button>
            <br />
</form>

 <div class="box links">
                    <div class="inbox">
                    
<script type="text/javascript">addthis_pub = '';addthis_language='en';</script>

<a href="http://www.addthis.com/bookmark.php" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" 
onmouseout="addthis_close()" onclick="return addthis_sendto()">
<img src="http://s7.addthis.com/static/btn/lg-share-en.gif" width="125" height="16" border="0" alt="" /></a>
<script type="text/javascript" src="http://s7.addthis.com/js/152/addthis_widget.js"></script>
<h3>Useful Links</h3>
                        <ul><li><a href="http://www.phoenix.edu/about_us/about_university_of_phoenix.html" target="_blank">About Us</a><br /></li><li><a href="http://www.phoenix.edu/campus-locations.html" target="_blank">Campus Locations</a><br /></li><li><a href="http://www.phoenix.edu/faculty/become_a_faculty_member/faculty-faq.html" target="_blank">Faculty FAQ’s</a><br /></li><li><a href="http://www.facultymatters.com/summer12" target="_blank">Faculty Matters magazine</a><br /></li><li><a href="http://facultyjobs-phoenix.com/article/facultyprofiles" target="_blank">Meet the Faculty</a><br /></li></ul>
                    </div><!--/.inbox-->
        </div><!--/.box .links--></div>
</div></div>
            
            
            
            
            </div><!--/.contents-->

         
            <div class="clear"></div>
