<div class="pageWrapper">
	<div class="header">
    	<a href="http://www.phoenix.edu/" target="blank"><img src="http://seostatic.tmp.com/job-images/3326/UP_logo.jpg" alt="University of Phoenix" /></a>
        <ul>
    <li class="first"><a href="http://www.phoenix.edu/faculty/become-a-faculty-member/doctoral-become-a-faculty-member.html" target="_blank">Become a Doctoral Faculty Member</a></li>
    <li><a href="http://www.phoenix.edu/faculty/become-a-faculty-member/teach-online-become-faculty-member.html" target="_blank">Become an Online Faculty Member</a></li>
    <li class="last"><a href="http://www.phoenix.edu/faculty/become-a-faculty-member.html" target="_blank">Become a Campus Faculty Member</a></li>
</ul>
    </div><!--/.header-->
    <div class="col-left">
    	<a href="/category">Search by Category</a>
		<a href="/location">Search by Location</a>
		<a href="#">Search Recent Jobs</a>
    </div>
    <div class="col-middle">
    	    <div id="searchblock" class="clearfix">
        <div class="wrapper">
            <form method="post" action="/search/" class="searchbar">
                <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
                <button type="submit" id="submit" value="search">search</button>
                <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
                    <?php
                      $dropEntry = '<option value=""></option>';
                    foreach ($this->dropdownLocations as $dropdownLocations): 
                      $val = Clean::uristub($dropdownLocations['location']);
                      $dropEntry .= '<option value="' . urlencode($dropdownLocations['location']) . '"';
                      $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
                      $dropEntry .= Clean::xss($dropdownLocations['location']);
                      $dropEntry .= '</option><br />'; 
                      endforeach; 
                      echo $dropEntry;
                      ?>
                </select>
                <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
                    <?php
                      $dropEntry = '<option value=""></option>';
                    foreach ($this->dropdownCategories as $dropdownCategories): 
                      $val = Clean::uristub($dropdownCategories['category']);
                      $dropEntry .= '<option value="' . urlencode($dropdownCategories['category']) . '"';
                      $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
                      $dropEntry .= Clean::xss($dropdownCategories['category']);
                      $dropEntry .= '</option><br />'; 
                      endforeach; 
                      echo $dropEntry;
                      ?>
                </select>
            </form>
        </div>
    </div>
    <div class="wrapper content">
        <?php if (isset($this->results)): ?>
        <div class="leftcolumn">
            <h2><?php echo Clean::deuristub($this->category); ?></h2>
            <h5>Showing <strong><?php echo count($this->results); ?></strong> matching jobs</h5>
            <?php if (!empty($this->results)): ?>
            <ul id="searchresults">
                
                <?php
                $alt = false;
                foreach ($this->results as $result):
                    $date_posted = $result['date_posted'];
                    $location = $result['location'];
                    $category = $result['category'];
                    $schedule = $result['schedule'];
    
                    // fix the date
                    $date_posted = (int) trim($date_posted);
                ?>
                    <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                        <span class="date"><?php echo !empty($date_posted) ? date('F j Y', $date_posted) : ''; ?></span>
                        <h3 class="job-title"><?php echo $result['name']; ?></h3>
                        <?php
                        $url = '/job/details/';
                        if (!empty($location)) $url .= Clean::uristub($result['location']) . '/';
                        if (!empty($category)) $url .= Clean::uristub($result['category']) . '/';
                        $url .= $result['uristub'] . '/';
                        ?>
                        <a href="<?php echo $url; ?>" class="right">View Details</a>
                        <?php if (!empty($schedule)): ?>
                        <span class="schedule"><?php echo $result['schedule']; ?></span>
                        <?php endif; ?>
    
                        <?php if (!empty($location)): ?>
                        <span class="location"><?php echo $result['location']; ?></span>
                        <?php endif; ?>
                    </li>
                    <?php $alt = !$alt; ?>
                <?php endforeach; ?>
            </ul>
            <?php else: ?>
            <p>No jobs currently exist in the specified category.</p>
            <?php endif; ?>
        </div>
        <?php else: ?>
            <div class="leftcolumn">
            <?php if (!empty($this->categories)): ?>
                <h2>Job Categories</h2>
                <ul class="alternating">
                    <?php $alt = false; ?>
                    <?php foreach ($this->categories as $category): ?>
                    <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                        
                        <?php
                        $url = '/jobs/' . str_replace("%2F", "_", urlencode($category['category'])) . '/';
                        ?>
                        <a href="<?php echo $url; ?>"><?php echo Clean::xss($category['category']); ?></a>
                    </li>
                    <?php $alt = !$alt; ?>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <h3>No categories currently exist</h3>
                <p>It does not appear as though any jobs currently exist.</p>
            <?php endif; ?>
            </div>
        <?php endif; ?>
        <?php if (!empty($this->locations)): ?>
        <div class="rightcolumn">
            <h4>Popular Job Locations</h4>
            <ul>
                <?php foreach ($this->locations as $location): ?>
                <?php $url = '/jobs/location/' . urlencode($location['location']) . '/'; ?>
                <li><a href="<?php echo $url; ?>"><?php echo Clean::xss($location['location']); ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
    </div>
    </div>
    <div id="col-right">   
    	<div class="box links">
        	<div class="inbox">
            	<script type="text/javascript">addthis_pub = '';addthis_language='en';</script>
				<a href="http://www.addthis.com/bookmark.php" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" onmouseout="addthis_close()" onclick="return addthis_sendto()"><img src="http://s7.addthis.com/static/btn/lg-share-en.gif" width="125" height="16" border="0" alt="" /></a>
				<script type="text/javascript" src="http://s7.addthis.com/js/152/addthis_widget.js"></script>
				<div class="box subscribe">
                	<div class="inbox">
                    	<h2>Sign Up for Job Alerts and News</h2>
                        <label for="txtEmail">Sign up here for email alerts and University of Phoenix news.</label>
                        <input id="txtEmail" type="text" value="Email address..." name="txtEmail" onclick="if(this.value=='Email address...'){this.value=''}" />
                        <input id="btnSubscribe" class="submit" type="button" name="btnSubscribe" value="Subscribe"  onclick="IsSEOSitesUserExists();"/>
                        <div class="sharedLinks">
                            <a class="add-to-google" target="_blank" href="http://www.google.com/ig/add?feedurl=http://facultyjobs-phoenix.com/RSS"><img class="add-to-google-img" src="http://seostatic.tmp.com/job-images/addGoogle-en.gif" alt="Add to Google" width="104" height="17" border="0"/></a>
                            <a class="subscribe-rss" target="_blank" href="/RSS"><img class="subscribe-rss-img" src="http://seostatic.tmp.com/job-images/rssFeed.gif" alt="Subscribe to RSS feed" width="17" height="17" border="0" /></a>
						<!-- AddThis Button BEGIN -->

						<!-- AddThis Button END -->
                        </div>
                	</div>
                </div>
                <h3>Useful Links</h3>
                <ul>
                	<li><a href="http://www.phoenix.edu/about_us/about_university_of_phoenix.html" target="_blank">About Us</a><br /></li>
                    <li><a href="http://www.phoenix.edu/campus-locations.html" target="_blank">Campus Locations</a><br /></li>
                    <li><a href="http://www.phoenix.edu/faculty/become_a_faculty_member/faculty-faq.html" target="_blank">Faculty FAQ’s</a><br /></li>
                    <li><a href="http://www.facultymatters.com/summer12" target="_blank">Faculty Matters magazine</a><br /></li>
                    <li><a href="http://facultyjobs-phoenix.com/article/facultyprofiles" target="_blank">Meet the Faculty</a><br /></li>
              	</ul>
        	</div><!--/.inbox-->
    	</div><!--/.box .links-->
    </div>
</div><!--pageWrapper-->
<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">
$(function() {
    $('a[rel=facebox]').facebox();
});

// sharethis
var switchTo5x=true;
var __st_loadLate=true;
</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
<script>
var options= {
    "publisher":"6e854950-d4af-4c0e-b499-499bef1829ce",
    "position":"left",
    "ad": {
        "visible":false,
        "openDelay":"5",
        "closeDelay":"0"
    },
    "chicklets": {
        "items": [
            "facebook",
            "twitter",
            "gbuzz",
            "linkedin",
            "email",
            "sharethis",
            "plusone_button",
            "fblike_button"
        ]
    },
};

var st_hover_widget = new sharethis.widgets.hoverbuttons(options);

stLight.options({
    publisher:'6e854950-d4af-4c0e-b499-499bef1829ce',
    theme: '2',
    doneScreen: 'false',
    embeds: 'true'
});
</script>
<?php $this->placeholder('js')->captureEnd(); ?>