<div class="headersearch" id="pagesearch">
        <div class="searchbox_header_page pagebox" id="category">
          <ul class='sf-menu'><li><h3><a href="/category">Search Jobs by Category »</a></h3>
</li>
</ul>
        </div>
        <div class="searchbox_header_page pagebox" id="location">
<ul class='sf-menu'><li>          <h3><a href="/location">Search Jobs by Location »</a></h3>
</li>
</ul>

            
        </div>
        <div class="searchbox_header_page pagebox" id="listings">
          <h3><a href="/jobs/all">Search All Apollo Jobs »</a></h3>
        </div>
      </div>