
<p>
  <span style="font-size:18px; font-weight:bold; margin-bottom:5px;">About Us</span><br />
  Apollo Group, Inc. was founded in 1973 in response to a gradual shift in higher education demographics from a student
  population dominated by youth to one in which approximately half the students are adults and over 80 percent of whom work full-time.
</p>
<p>
  Apollo's founder, John Sperling, believed -- and events proved him right -- that lifelong employment with a single employer would be replaced by lifelong learning and employment with a variety of employers. Lifelong learning requires an institution dedicated solely to the education of working adults.
</p>
<p>
  Today, Apollo Group, Inc., through its subsidiaries, University of Phoenix, Apollo Global, College for Financial Planning, and Institute for Professional Development, has established itself as a leading provider of higher education programs for working adults by focusing on servicing the needs of the working adult.
</p>

<div id="home_col_right" style="margin-left:0;">
  <p>
    <span style="font-size:18px; font-weight:bold; margin-bottom:5px;">Employer of Choice</span><br />
    Every day, the people of Apollo Group work hard to earn the label &quot;Employer of Choice.&quot; But what exactly does that mean?
  </p>
  <ul>
    <li>An atmosphere that's founded on fairness and respect</li>
    <li>A culture that thrives on commitment, enthusiasm, passion, and employee engagement</li>
    <li>An environment that embraces innovative ideas and people from diverse backgrounds</li>
    <li>A dynamic workplace that offers opportunities to enjoy your everyday opportunities while growing personally and professionally over the long term.</li>
  </ul>
  <br />In essence, being an Employer of Choice can mean something unique for each of us.
</div>