			<div id="footer">
				<p class="left">
					&copy; <?php echo date('Y'); ?>
					<?php
					if (!empty($this->theme['website'])) {
						$text = '<a href="' . $this->theme['website'] . '" target="_blank">';
						$text .= !empty($this->theme['company']) ? $this->theme['company'] : 'JobCastle';
						$text .= '</a>';
					} else {
						$text = !empty($this->theme['company']) ? $this->theme['company'] : 'JobCastle';
					}
					echo $text;
					?>. All rights reserved.
				</p>
				<p class="right">Powered by JobCastle</p>
			</div>
		</div>
		<!-- wrapper ends -->

	</div>
	<!-- #hld ends -->

	<!--[if IE]><script type="text/javascript" src="/js/admin/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="/js/admin/jquery.js"></script>
	<script type="text/javascript" src="/js/admin/global.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.img.preload.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.filestyle.mini.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.wysiwyg.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.date_input.pack.js"></script>
	<script type="text/javascript" src="/js/admin/facebox.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.visualize.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.visualize.tooltip.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.select_skin.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.tablesorter.min.js"></script>
	<script type="text/javascript" src="/js/admin/ajaxupload.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.pngfix.js"></script>
	<script type="text/javascript" src="/js/admin/custom.js"></script>
	<?php echo $this->partial('partials/global/error-form.phtml', array('errors' => !empty($this->errors) ? $this->errors : NULL)); ?>
	<?php
	echo $this->inlineScript();
	echo $this->placeholder('js');
	?>
</body>
</html>