<!-- <h2 align="center" style="padding-top:10px; text-align:center;">Search our Job Listings by Title, Location, or Category</h2> -->
  <div id="searchblock" class="nomobile">
    <div class="wrapper">
      <form method="post" action="/search/" class="searchbar <?php echo !empty($this->searchFormClass) ? $this->searchFormClass : null; ?>">
        <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
        <button type="submit" id="submit" value="search"><div class="mobileonly">search</div></button>
        <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
        <?php
          $dropEntry = '<option value=""></option>';
          foreach ((array)$this->dropdownLocations as $dropdownLocations) {
            $val = Clean::uristub($dropdownLocations['location']);
            $dropEntry .= '<option value="' . urlencode($dropdownLocations['location']) . '"';
            $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
            $dropEntry .= Clean::xss($dropdownLocations['location']);
            $dropEntry .= '</option><br />';
          }
          echo $dropEntry;
        ?>
        </select>
        <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
        <?php
          $dropEntry = '<option value=""></option>';
          foreach ((array)$this->dropdownCategories as $dropdownCategories) {
            $val = Clean::uristub($dropdownCategories['category']);
            $dropEntry .= '<option value="' . urlencode($dropdownCategories['category']) . '"';
            $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
            $dropEntry .= Clean::xss($dropdownCategories['category']);
            $dropEntry .= '</option><br />';
          }
          echo $dropEntry;
        ?>
        </select>
      </form>
      <?php if (!isset($this->showSearchButtons) || $this->showSearchButtons): ?>
      <div id="pagesearch">
        <div class="searchbox_header_page pagebox" id="category">
          <h3><a href="/category">Search Jobs by Category >></a></h3>
        </div>
        <div class="searchbox_header_page pagebox" id="location">
          <h3><a href="/location">Search Jobs by Location >></a></h3>
        </div>
        <div class="searchbox_header_page pagebox" id="listings">
          <h3><a href="/jobs/all">Search All Apollo Jobs >></a></h3>
        </div>
      </div>
      <?php endif; ?>
    </div>
  </div>
  
  <div class="mobileonly">

    <div id="pagesearch"><form method="post" action="/search/" class="searchbar <?php echo !empty($this->searchFormClass) ? $this->searchFormClass : null; ?>">
    <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
    <button type="submit" id="submit" value="search"><div id="mobileonly">search</div></button>
    <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
      <?php
          $dropEntry = '<option value=""></option>';
          foreach ((array)$this->dropdownLocations as $dropdownLocations) {
            $val = Clean::uristub($dropdownLocations['location']);
            $dropEntry .= '<option value="' . urlencode($dropdownLocations['location']) . '"';
            $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
            $dropEntry .= Clean::xss($dropdownLocations['location']);
            $dropEntry .= '</option><br />';
          }
          echo $dropEntry;
        ?>
    </select>
    <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
      <?php
          $dropEntry = '<option value=""></option>';
          foreach ((array)$this->dropdownCategories as $dropdownCategories) {
            $val = Clean::uristub($dropdownCategories['category']);
            $dropEntry .= '<option value="' . urlencode($dropdownCategories['category']) . '"';
            $dropEntry .= (!empty($category) && $category == $val) ? ' selected="selected">' : '>';
            $dropEntry .= Clean::xss($dropdownCategories['category']);
            $dropEntry .= '</option><br />';
          }
          echo $dropEntry;
        ?>
    </select>
    </form>
    <?php if (!isset($this->showSearchButtons) || $this->showSearchButtons): ?>
      <div class="searchbox_header_page pagebox" id="category">
        <h3><a href="/category">Search Jobs by Category </a></h3>
      </div>
      <div class="searchbox_header_page pagebox" id="location">
        <h3><a href="/location">Search Jobs by Location </a></h3>
      </div>
      <div class="searchbox_header_page pagebox" id="listings">
        <h3><a href="/jobs/all">Search All Apollo Jobs </a></h3>
      </div>
    </div>
    <?php endif; ?>
  </div>