<?php
$protocol = 'http';
if ($_SERVER['SERVER_PORT'] == 443 || (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on')) {
	$protocol .= 's';
	$protocol_port = $_SERVER['SERVER_PORT'];
} else $protocol_port = 80;
$host = $_SERVER['HTTP_HOST'];
$port = $_SERVER['SERVER_PORT'];
$request = $_SERVER['PHP_SELF'];
$baseurl = $protocol . '://' . $host . ($port == $protocol_port ? '' : ':' . $port) . '/user/reset/';
?>
Hello <?php echo $this->email; ?>,<br /><br />

We believe you may have forgotten your password.<br /><br />
Please click the below link to reset your password:<br /><br />

<?php echo $baseurl . $this->unique_id; ?><br /><br />