        <div class="container">
            <div id="footer" class="clearfix" style="color:#dee2e3; font-size:11px; font-family:Arial, Helvetica, sans-serif;">
                <div class="wrapper">
                    <div class="column_left">
                        Job Search Links
                        <span>
                            <a href="/category">Jobs by Category » &nbsp; &nbsp; </a><br />
                            <a href="/location">Jobs by Location » &nbsp; &nbsp; </a><br />
                            <a href="/jobs/all">All Apollo Jobs » &nbsp; &nbsp; </a><br />
                        </span>
                    </div>
                    <div class="column_middle">
                       Quick Links
                        <span>
                             <a href="http://www.apollogrp.edu/">Corporate Site</a>
                            <a href="http://www.apollogrp.edu/careers/wellness-program">Wellness Program</a>
                            <a href="http://www.apollogrp.edu/careers/workplace-awards">Workplace Awards</a>
                            
                        </span>
                    </div>
                  <div class="column_right_middle">
                    Policy Links   
                    <a href="http://www.apollogrp.edu/privacy-policy">Privacy Policy</a>             
                    <a style="width:300px;" href="http://www.apollogrp.edu/sites/default/files/files/Apollo-Group-Website-Terms-and-Conditions-of-Use-2011-03-01.pdf">Terms & Conditions</a>
                  </div>
                      <div class="column_right">
                    <a href="http://apollogrp.edu/" target="_blank"><img style="float:left;" src="/images/logo_white.png" /></a>

                    </div>
               
              </div>
            </div>
        </div>