<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<?php
		$title = !empty($this->theme['company']) ? $this->theme['company'] . ' | Jobs' : 'Apollo Group Careers | Jobs';
		if (!empty($this->title)) {
			foreach ((array) $this->title as $t) {
				$title .= ' | ' . Clean::xss($t);
			}
		}
		?>
		<meta charset="utf-8" />
		<meta content="<?php echo $this->csrfToken(); ?>" name="csrf-token" />
		<meta name="description" content="<?php echo !empty($this->description) ? $this->escape(substr($this->description, 0, 155)) : ''; ?>" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="" />
		<meta property="og:image" content="<?php echo !empty($this->theme['logo']) ? $this->escape($this->serverUrl() . $this->theme['logo']) : ''; ?>" />
		<meta property="og:site_name" content="<?php echo !empty($this->theme['company']) ? $this->escape($this->theme['company']) : 'JobCastle'; ?>" />
		<meta property="og:title" content="<?php echo $title; ?>" />
		<meta property="og:description" content="<?php echo !empty($this->description) ? $this->escape(substr($this->description, 0, 155)) : ''; ?>" />
		<meta property="fb:admins" content="<?php echo !empty($this->og['admin']) ? $this->escape($this->og['admin']) : ''; ?>" />
		<!-- will likely want application icon images for mobile -->
		<?php
		$this->headTitle((!empty($this->theme['company']) ? $this->theme['company'] . ' | Jobs' : 'Apollo Group Careers'), 'APPEND')->setSeparator(' | ');
		if (!empty($this->title)) {
			foreach ((array) $this->title as $title) {
				$this->headTitle()->append($title);
			}
		}
		echo $this->headTitle();

        $this->headLink()->prependStylesheet('/css/chosen.css');
        $this->headLink()->prependStylesheet('/css/mobile.css');

		/*
		$this->headLink()->prependStylesheet('/css/admin/black/facebox.css');
        $this->headLink()->prependStylesheet('/css/chosen.css');
		$this->headLink()->prependStylesheet('/css/theme.css');
		$this->headLink()->prependStylesheet('/css/global.css');
		*/

		echo $this->headLink();
		echo $this->placeholder('css');
		echo $this->headScript();
		?>
	</head>
	<body id="<?php echo $this->bodyID; ?>">
		<div id="<?php echo !empty($this->containerClass) ? $this->containerClass : 'container'; ?>">
			<div id="header" style="margin-left:auto; margin-right:auto; width:auto;">
			  <p align="center"><img src="/images/header-mobile.jpg" /></p>
			  <p align="center">Welcome to Apollo Group's mobile search site. </p>
			  <div id="toplinks"> 
			    <p><a href="<?php echo $this->serverUrl(); ?>">Home</a></p>
		        <p>&nbsp;</p>
			  </div>
			</div>